SET FOREIGN_KEY_CHECKS = 0;
ALTER TABLE cursos MODIFY id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE usuarios MODIFY id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE topicos MODIFY id BIGINT NOT NULL AUTO_INCREMENT;
SET FOREIGN_KEY_CHECKS = 1;